version: "3.9"

services:
  db:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./proxy/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
  app:
    build: ./proxy
    depends_on:
      - db
    command: npm start
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres
      - PG_PORT=5432
    expose:
      - "8000"
  nginx:
    depends_on:
      - app
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80